version: "3.8"
services:

  mysql-post:
    image: mysql:8
    container_name: mysql-post-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: postservice_db
    ports:
      - "3306:3306"

  mysql-review:
    image: mysql:8
    container_name: mysql-review-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: reviewservice_db
    ports:
      - "3307:3306"

  mysql-comment:
    image: mysql:8
    container_name: mysql-comment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: commentservice_db
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # mgmt UI
